# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180425_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='p3.jpg', upload_to=''),
        ),
    ]
